### ISSUE TITLE
Unable to get the Jade ID when running on testnet

### ISSUE THREAD

**Issue by grubles** [Blockstream/lwk#1]
Using LWK at e53494cf65b21d8af3720f2ab05d9008cc730348 on Ubuntu 23.10.

Running with `--network mainnet` works, but when trying using testnet I get this error: 

```
$ cli signer jade-id
{
  "code": -32013,
  "data": null,
  "message": "Jade Error: Jade Error: Error code: -32003 - message: Network type inconsistent with prior usage"
}
```

**Comment by delta1** [comment]
hey @grubles i think your jade needs to be initialized for testnet. i’m not sure what the suggested way to do that is, previously i did a factory reset, and then used the auth_user serial test to init for testnet

**Comment by grubles** [comment]
I've reset the Jade, created a new mnemonic, and ran the following:

```
$ cargo test serial::unlock -- --exact
```

This outputs

```
running 1 test                                                                                                                                                                         
test serial::unlock ... ignored, requires hardware jade connected via usb/serial to input pin
```

Am I missing a step?

**Comment by RCasatta** [comment]
Add `--include-ignored` at the end of the `cargo test` command

**Comment by grubles** [comment]
Ok adding that flag made the new PIN prompt appear on the Jade but the test times out before I can enter a PIN twice for confirmation. Another attempt left the Jade hanging at "Persisting PIN data"(?) after inputting the new PIN.

**Comment by grubles** [comment]
Thanks. I'm up and running now.
