### ISSUE TITLE
C# bindings

### ISSUE THREAD

**Issue by Kukks** [Blockstream/lwk#16]
Since you use uniffi for bindings, C# should be relatively easy to add support for.

**Comment by CEOWal** [comment]
Im Wallet

**Comment by CEOWal** [comment]
> Im Wallet

**Comment by RCasatta** [comment]
update: we have preliminary support for this https://github.com/Blockstream/lwk/blob/master/lwk_bindings/tests/bindings/list_transactions.cs

**Comment by RCasatta** [comment]
there is also a nuget package now https://www.nuget.org/packages/LiquidWalletKit/0.8.2
