### ISSUE TITLE
PSET to TX and back

### ISSUE THREAD

**Issue by apotdevin** [Blockstream/lwk#19]
In a remote signing env where the PSET is created on the server and sent to the client for signing, the flow I have in mind is:

1. Create PSET
2. Extract TX from the PSET
3. Send TX string to client
4. Client constructs PSET and signs it
5. Client extracts TX and sends the signed TX string back to us
6. We broadcast the TX

Now, the part I'm missing is how to go from a TX string to a PSET that can then be signed.

How could I go about that? Would this be the correct flow for remote signing?

**Comment by RCasatta** [comment]
The PSET is meant to be transferred around, extracting the transaction only before broadcasting

**Comment by apotdevin** [comment]
Got it - is there any way for me to turn the PSET into a buffer or string?

**Comment by apotdevin** [comment]
https://github.com/Blockstream/lwk/pull/20
