### ISSUE TITLE
Error doing a full scan with pending transactions

### ISSUE THREAD

**Issue by apotdevin** [Blockstream/lwk#21]
When I attempt to do a full scan `new EsploraClient(...).fullScan(wollet)` for a wallet that has an unconfirmed transaction I get the following error `"Unexpected error value: "Wollet(JsonFrom(Error("missing field 'block_height'", line: 1, column: 2850)))""`

**Comment by RCasatta** [comment]
I did the MR to fix this, wasm codebase is not yet on par with the base crate, especially regarding tests, please don't hesitate to open issues when you have bugs, we will try to fix as soon as possible
