### ISSUE TITLE
Drain wallet support

### ISSUE THREAD

**Issue by JoaoLobo94** [Blockstream/lwk#32]
There is currently no drain wallet support.

To emulate draining of a wallet I am currently running a "hack" where I loop over the total amount and subtract 1000 sats everytime lwk is not able to provide a valid pset. (I am working with lwk-dart bindings)

```
  Future<String> buildDrainWalletTx(TransactionBuilder params) async {
    var amount = params.amount;
    while (true) {
      try {
        final pset = await config.liquid.wallet.buildLbtcTx(
          sats: amount,
          outAddress: params.outAddress,
          feeRate: params.fee * 1000,
        );
        return pset;
      } catch (e) {
        if (amount > 0) {
          amount -= 1000;
        } else {
          if (e.toString().contains("InsufficientFunds")) {
            throw "Insufficient funds";
          }
          throw e.toString();
        }
      }
    }
  }
  
  ```
  
 In my wallet this kinda works but it is not perfect. There is always some outstanding balance that user cannot spend
  
![IMAGE 2024-05-20 15:59:17](https://github.com/Blockstream/lwk/assets/47111823/ca50d53d-ef71-4528-80f8-ef6983530631)

Do you have any solution to drain wallet?

**Comment by JoaoLobo94** [comment]
Update:

Pset building also returns insufficient funds error when we have 

EX: 6000 sats in the wallet

Total fee: 260 sats

Sending amount 5600 sats.

This means that there is outstanding unspendable balance in the wallet 🤔

**Comment by RCasatta** [comment]
We are releasing `drain` very soon

**Comment by LeoComandini** [comment]
If you can use lwk, you can do something like:
```
        let mut pset = self
            .tx_builder()
            .drain_lbtc_wallet()
            .drain_lbtc_to(address)
            .fee_rate(fee_rate)
            .finish()
            .unwrap();
```
See https://github.com/Blockstream/lwk/blob/master/lwk_test_util/src/lib.rs#L503

If you need a release, we can do one soon

**Comment by JoaoLobo94** [comment]
@i5hi will a release be needed to implement this in the bindings, or can we use master? Is this already in the plans for when lwk releases?

I can implement if not in the plans if you want 😀

**Comment by LeoComandini** [comment]
@JoaoLobo94 @i5hi latest release has drain support, closing
