### ISSUE TITLE
[feature request] Option to bypass signature "grinding"

### ISSUE THREAD

**Issue by miketlk** [Blockstream/lwk#37]
I'm using LWK to generate test vectors for an embedded Liquid app running on the Ledger Nano S platform. Unfortunately, the vendor-supplied SDK for this platform does not provide control over nonce (entropy) of ECDSA signature function. Thus, to make test vectors with reproducible signatures, I have to patch LWK manually changing `secp.sign_ecdsa_low_r()` to `secp.sign_ecdsa()`.

It would be nice if the external API of LWK had an optional flag allowing bypassing signature grinding.

Here is the line I'm modifying:
https://github.com/Blockstream/lwk/blob/91e4224dea7ea483f753561b95a46353380106b4/lwk_signer/src/software.rs#L157

**Comment by LeoComandini** [comment]
Opened #44 which allows to have the sw signer to produce signatures without grinding "r".

Most wallets grind "r", so not grinding "r" is not ideal, but if Ledger does not allow doing so there is not much we can do.

Anyway we should make such signature possible

**Comment by LeoComandini** [comment]
Done in #44, closing
