### ISSUE TITLE
Check lwk compatibility with confidential transactions discount

### ISSUE THREAD

**Issue by YusukeShimizu** [Blockstream/lwk#48]
## Description

[Elements version 23.2.2](https://github.com/ElementsProject/elements/releases/tag/elements-23.2.2) and later introduce a discount for confidential transactions.
Would it be possible to add a way for users to check if their lwk version supports the confidential transactions discount?  

## Background

[In peerswap](https://github.com/ElementsProject/peerswap), we're looking to implement a feature that adjusts the default fee rate based on whether confidential transactions are supported.  
Having a way to verify lwk compatibility would be very helpful for this.

For your reference, I've attached a link to a pull request that addresses this in the context of elements.
https://github.com/ElementsProject/peerswap/pull/304

**Comment by RCasatta** [comment]
We should provide a method on the `TxBuilder` to opt in though...

**Comment by YusukeShimizu** [comment]
My understanding is that transactions created with the current send method do not have the CT discount applied.

In this case, can I expect that a parameter will be added that allows options to be applied?

**Comment by RCasatta** [comment]
Yes, current transactions are created without the discount. There will be an option in the tx builder to enable the discount. Will be default off until the discount isn't deployed in the live network and default on after.

@LeoComandini may work on that in the next days

**Comment by YusukeShimizu** [comment]
Is it possible in LDK to test without actually broadcasting a tx, similar to the testmempoolaccept for elements?

Background:
In peerswap's Negotiation, we need to calculate the estimated tx fee and send it to the peer, and I'm considering using it for that purpose.

**Comment by LeoComandini** [comment]
@YusukeShimizu we have 

    lwk_cli wallet broadcast -w WALLET_NAME -p PSET --dry-run

however it does not allow you to get the fee out of the transaction.

Instead you should use

    lwk_cli wallet pset-details -w WALLET_NAME -p PSET
   
and get the fee from that.

Note that in Liquid the fee is explicit, so it's not an estimate.

**Comment by YusukeShimizu** [comment]
Thank you.

While I understand that pset-details can confirm the fee of the created transaction, it might be slightly different from my intention.

I'd like to check if the connected elements support ct discount. Is there a way to do this?
I believe [the approach you suggested](https://github.com/Blockstream/lwk/issues/48#issuecomment-2268267093) below is the way to go, so I think I need something similar to `testmempoolaccept`.

> Another approach at the user level may be the "Ask forgiveness not permission" one, trying to broadcast with the discounted fee and if the broadcast fail try with the non-discounted one.

I'm not familiar with Rust, but from looking at the lwk code, I don't think `lwk_cli wallet broadcast -w WALLET_NAME -p PSET --dry-run` can tell whether the actually connected elements support ct discount.

**Comment by YusukeShimizu** [comment]
In peerswap, we've decided to enforce CT discount settings by bumping the protocol version.  
So, you can disregard the above issue.

I would appreciate it if you could let me know when the CT discount option is added to the `send` method.

**Comment by LeoComandini** [comment]
@YusukeShimizu CT discount opt-in support was added in https://github.com/Blockstream/lwk/commit/d1e0a5c3c4ea4cdf426e7e316858f58f948685d4
```
$ lwk_cli wallet send -w WALLET --recipient ADDRESS:SATS:ASSET --enable-ct-discount
```
In the future, once it will be broadly accepted in the network, we'll make ct-discount the default.

Closing
