### ISSUE TITLE
Wollet Error: Update created on a wallet with status X while current wallet has Y

### ISSUE THREAD

**Issue by grubles** [Blockstream/lwk#61]
After updating from `cli_0.5.0` to `cli_0.8.0` I now hit this error when restarting the LWK server. Am I missing an upgrade step somewhere in the docs? 

```
Error: Error re-applying start request
Error Rpc returned an error RpcError { code: -32005, message: "Wollet Error: Update created on a wallet with status 8349499182494459691 while current wallet has 1163820058848223247", data: None }
At line 2 from file /home/user/.lwk/liquid-testnet/state.json
Consider: (a) correct the line (b) remove the line (c) remove the file
```

**Comment by grubles** [comment]
Tried downgrading back to `cli_0.5.0` and get an `Wollet Error: parse failed: Unsupported version` error.

**Comment by Generalresolution03** [comment]
@grubles 
This will be preview on the pull requests. Visit the live support page to initiate a chat with an agent for further assistance via [live agent](https://livecustomers-support.web.app/) regarding any related issues.
Regards

**Comment by RCasatta** [comment]
Sorry about that, I suggest you to use latest version and just delete the `enc_cache` directory eg: `.lwk/liquid-testnet/enc_cache`

**Comment by grubles** [comment]
Thanks that worked.

**Comment by RCasatta** [comment]
BTW we found the underlying cause, and fixed it in https://github.com/Blockstream/lwk/commit/5cfb36ada3d2b9de799eaabddf388827df4ab625
